from stack import Stack
import pytest

def test_empty():
    s = Stack()
    assert(s.isEmpty() == True)
    assert(s.items == [])

def test_push_one():
    s = Stack()
    s.push(1)
    assert(s.isEmpty() == False)
    assert(s.items == [1])

def test_pop_one():
    s = Stack()
    s.push(3)
    assert(s.isEmpty() == False)
    assert(s.items == [3])
    s.pop()
    assert(s.isEmpty() == True)
    assert(s.items == [])

def test_push_multiple():
    s = Stack()
    s.push(1)
    assert(s.isEmpty() == False)
    assert(s.items == [1])
    s.push(2)
    assert(s.isEmpty() == False)
    assert(s.items == [1,2 ])
    s.push(3)
    assert(s.isEmpty() == False)
    assert(s.items == [1, 2, 3])
    s.push(4)
    assert(s.isEmpty() == False)
    assert(s.items == [1, 2, 3, 4])
    s.push(5)
    assert(s.isEmpty() == False)
    assert(s.items == [1,2 ,3, 4, 5])

def test_pop_multiple():
    s = Stack()
    s.push(1)
    assert(s.isEmpty() == False)
    assert(s.items == [1])
    s.push(2)
    assert(s.isEmpty() == False)
    assert(s.items == [1, 2 ])
    s.push(3)
    assert(s.isEmpty() == False)
    assert(s.items == [1, 2, 3])
    s.push(4)
    assert(s.isEmpty() == False)
    assert(s.items == [1, 2, 3, 4])
    s.push(5)
    assert(s.isEmpty() == False)
    assert(s.items == [1, 2 ,3, 4, 5])
    s.pop()
    assert(s.isEmpty() == False)
    assert(s.items == [1, 2 ,3, 4])
    s.pop()
    assert(s.isEmpty() == False)
    assert(s.items == [1, 2 ,3])
    s.pop()
    assert(s.isEmpty() == False)
    assert(s.items == [1, 2])
    s.pop()
    assert(s.isEmpty() == False)
    assert(s.items == [1])
    s.pop()
    assert(s.isEmpty() == True)
    assert(s.items == [])